name: php-lambda-api

networks:
  php-lambda-api-net:
    name: php-lambda-api-net

volumes:
  php-lambda-api-pgdata:
    name: php-lambda-api-pgdata

services:
  api:
    # https://bref.sh/docs/local-development
    # https://hub.docker.com/u/bref
    image: bref/php-84-fpm-dev:2.3.34
    container_name: php-lambda-api-app
    hostname: php-lambda-api-app
    ports: ["8000:8000"]
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
      APP_TZ: Europe/Budapest
      LOG_LEVEL: debug
      APP_ENV: local
      AWS_REGION: eu-central-1
      # Database connection
      DB_HOST: php-lambda-api-db
      DB_PORT: "5432"
      DB_NAME: aurora_postgresql_db
      DB_USER: app_user
      DB_PASSWORD: app_pass
      # Local DB is nonâ€‘TLS for simplicity; keep sslmode=require in prod
      DB_SSLMODE: disable
    volumes:
      # Mount project code read-only, Lambda-like
      - ../../app:/var/task:ro
    depends_on:
      db:
        condition: service_healthy
    networks: [php-lambda-api-net]

  db:
    image: postgres:17.4
    container_name: php-lambda-api-db
    hostname: php-lambda-api-db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: aurora_postgresql_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 3s
      timeout: 2s
      retries: 30
    volumes:
      - php-lambda-api-pgdata:/var/lib/postgresql/data
    networks: [php-lambda-api-net]
